name: Build

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  Build:
    name: npm run build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use node 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
